openapi: 3.0.0
info:
  title: Snowflake ID Generator API
  description: API for generating unique Snowflake IDs
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
    description: "Local server"
paths:
  /generate-id:
    get:
      summary: Generate a unique Snowflake ID
      operationId: generateId
      responses:
        '200':
          description: Successful response with a unique ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique Snowflake ID
                    example: 123456789012345
        '500':
          description: Internal server error
        '400':
          description: Bad request
