replicaCount: 2

image:
  repository: bymerk/snowflake
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  ports:
    http:
      port: 8080
      targetPort: 8080
    grpc:
      port: 5051
      targetPort: 5051
    metrics:
      port: 9000
      targetPort: 9000


resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

probes:
  liveness:
    path: /live
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


nodeSelector: {}
tolerations: []
affinity: {}
